version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: paul
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: exem_data
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: exem_data
      DB_USER: paul
      DB_PASSWORD: secret
    depends_on:
      - db
    volumes:
      - ./app:/app

volumes:
  db_data: